//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentInquiry.Suspense {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Suspense.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAreas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProvinces", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetProvinces();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreasByProvince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAreasByProvince(string prov_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAgents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllAgents(string prov_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOfflinePayments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOfflinePayments(PaymentInquiry.Suspense.Request req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOnlinePayments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOnlinePayments(PaymentInquiry.Suspense.Request req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOfflinePaymentsTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOfflinePaymentsTest(PaymentInquiry.Suspense.Request req);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaField;
        
        private bool status_areaField;
        
        private System.DateTime from_dateField;
        
        private bool status_from_dateField;
        
        private System.DateTime to_dateField;
        
        private bool status_to_dateField;
        
        private decimal amountField;
        
        private bool status_amountField;
        
        private string account_numberField;
        
        private bool status_account_numberField;
        
        private string counter_numberField;
        
        private bool status_counter_numberField;
        
        private string stub_numberField;
        
        private bool status_stub_numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool status_area {
            get {
                return this.status_areaField;
            }
            set {
                this.status_areaField = value;
                this.RaisePropertyChanged("status_area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime from_date {
            get {
                return this.from_dateField;
            }
            set {
                this.from_dateField = value;
                this.RaisePropertyChanged("from_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool status_from_date {
            get {
                return this.status_from_dateField;
            }
            set {
                this.status_from_dateField = value;
                this.RaisePropertyChanged("status_from_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime to_date {
            get {
                return this.to_dateField;
            }
            set {
                this.to_dateField = value;
                this.RaisePropertyChanged("to_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool status_to_date {
            get {
                return this.status_to_dateField;
            }
            set {
                this.status_to_dateField = value;
                this.RaisePropertyChanged("status_to_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool status_amount {
            get {
                return this.status_amountField;
            }
            set {
                this.status_amountField = value;
                this.RaisePropertyChanged("status_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string account_number {
            get {
                return this.account_numberField;
            }
            set {
                this.account_numberField = value;
                this.RaisePropertyChanged("account_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool status_account_number {
            get {
                return this.status_account_numberField;
            }
            set {
                this.status_account_numberField = value;
                this.RaisePropertyChanged("status_account_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string counter_number {
            get {
                return this.counter_numberField;
            }
            set {
                this.counter_numberField = value;
                this.RaisePropertyChanged("counter_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool status_counter_number {
            get {
                return this.status_counter_numberField;
            }
            set {
                this.status_counter_numberField = value;
                this.RaisePropertyChanged("status_counter_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string stub_number {
            get {
                return this.stub_numberField;
            }
            set {
                this.stub_numberField = value;
                this.RaisePropertyChanged("stub_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool status_stub_number {
            get {
                return this.status_stub_numberField;
            }
            set {
                this.status_stub_numberField = value;
                this.RaisePropertyChanged("status_stub_number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : PaymentInquiry.Suspense.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<PaymentInquiry.Suspense.WebServiceSoap>, PaymentInquiry.Suspense.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAreas() {
            return base.Channel.GetAreas();
        }
        
        public System.Data.DataSet GetProvinces() {
            return base.Channel.GetProvinces();
        }
        
        public System.Data.DataSet GetAreasByProvince(string prov_code) {
            return base.Channel.GetAreasByProvince(prov_code);
        }
        
        public System.Data.DataSet GetAllAgents(string prov_code) {
            return base.Channel.GetAllAgents(prov_code);
        }
        
        public string GetOfflinePayments(PaymentInquiry.Suspense.Request req) {
            return base.Channel.GetOfflinePayments(req);
        }
        
        public System.Data.DataSet GetOnlinePayments(PaymentInquiry.Suspense.Request req) {
            return base.Channel.GetOnlinePayments(req);
        }
        
        public string GetOfflinePaymentsTest(PaymentInquiry.Suspense.Request req) {
            return base.Channel.GetOfflinePaymentsTest(req);
        }
    }
}
